### ISSUE TITLE
Uncaught node.js error

### ISSUE THREAD

**Issue by bastienpetit** [julienma/Bridget#17]
When I launch Bridget, I have this error:

Uncaught node.js Error 
Error: The response was invalid GNTP.
    at Socket.<anonymous> (/Users/bpetit/Desktop/Bridget-1.app/Contents/Resources/app.nw/node_modules/growler/lib/growler.js:375:23)
    at Socket.g (events.js:192:14)
    at Socket.EventEmitter.emit (events.js:96:17)
    at net.js:358:10
    at process._tickCallback (node.js:180:9)

**Comment by bastienpetit** [comment]
And it works ! It wooooooorks !
